-- CampusCrave core schema.
-- H2 in dev, Postgres in prod — everything here is common-dialect SQL.

create table students (
    id            bigint generated by default as identity primary key,
    roll_number   varchar(20)  not null unique,
    name          varchar(120) not null,
    email         varchar(160) not null,
    hostel_block  varchar(20)
);

create table wallets (
    id             bigint generated by default as identity primary key,
    student_id     bigint  not null unique references students (id),
    balance_rupees int     not null default 0
);

create table dishes (
    id                bigint generated by default as identity primary key,
    name              varchar(120) not null,
    description       varchar(300),
    price_rupees      int          not null,
    category          varchar(40)  not null,
    vegetarian        boolean      not null,
    stock             int          not null default 0,
    emoji             varchar(8),
    prep_minutes      int          not null default 10,
    wednesday_special boolean      not null default false,
    active            boolean      not null default true
);

create table orders (
    id           bigint generated by default as identity primary key,
    student_id   bigint      not null references students (id),
    status       varchar(20) not null,
    total_rupees int         not null,
    token_number int         not null,
    pickup_block varchar(20),
    created_at   timestamp   not null
);

create table order_items (
    id                bigint generated by default as identity primary key,
    order_id          bigint not null references orders (id),
    dish_id           bigint not null references dishes (id),
    quantity          int    not null,
    unit_price_rupees int    not null
);

create table canteen_config (
    id                bigint  primary key,
    order_cutoff      time    not null,
    rush_start        time    not null,
    rush_end          time    not null,
    max_active_orders int     not null,
    accepting_orders  boolean not null default true
);

create index idx_orders_student on orders (student_id);
create index idx_orders_status on orders (status);
create index idx_order_items_order on order_items (order_id);
create index idx_order_items_dish on order_items (dish_id);
